> ### **Assignment 2 - Numpy Array Operations** 



# Top 5 Numpy functions you need to know


### 5 useful Numpy functions

NumPy is a python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

- np.matmul
- np.reshape
- np.stack
- np.mean
- np.linalg.solve

In [5]:
!pip install jovian --upgrade -q

In [6]:
import jovian

In [7]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "akhilesharma47/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/akhilesharma47/numpy-array-operations


'https://jovian.ml/akhilesharma47/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [8]:
import numpy as np

In [9]:
# List of functions explained 
function1 = np.matmul
function2 = np.reshape
function3 = np.stack
function4 = np.mean
function5 = np.linalg.solve

## Function 1 - np.matmul

function to multiply two matrices

In [10]:
# Example 1 - working 
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.matmul(arr1, arr2)

array([[21., 24., 27.],
       [47., 54., 61.]])

The function performs matrix multiplication of two matrices and returns the result. Here a 2x2 matrix when multiplied with a 2x3 matrix gives a 2x3 matrix as result.

In [11]:
# Example 2 - working
a = np.random.rand(4,5)
b = np.random.rand(5,2)
np.matmul(a,b)

array([[1.88977877, 1.88815057],
       [1.6853393 , 1.59832759],
       [1.01972388, 0.8871947 ],
       [1.02343918, 1.06963227]])

Here a random 4x5 matrix when multiplied with a 5x2 matrix gives a 4x2 matrix as result.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7]]

np.matmul(arr1, arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

Here we are trying to multiply a 2x2 matrix with a 1x3 matrix but for matrix to be multiplicable the follwing condition is necessary :
(a,b) * (b,c) = (a,c) where a,b,c are dimensions of the matrix.

This function can be used to multiply martix.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "akhilesharma47/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/akhilesharma47/numpy-array-operations


'https://jovian.ml/akhilesharma47/numpy-array-operations'

## Function 2 - np.reshape

This function is used to reshape a matrix without changing the data.

In [14]:
# Example 1 - working
arr = np.random.rand(3,2)
print('Initial array shape : ',arr.shape,'\n',arr,'\n')
reshaped = np.reshape(arr,(2,3))
print('Output array shape : ',reshaped.shape,'\n',reshaped)

Initial array shape :  (3, 2) 
 [[0.39021156 0.70666908]
 [0.20093048 0.86041181]
 [0.22432493 0.64168503]] 

Output array shape :  (2, 3) 
 [[0.39021156 0.70666908 0.20093048]
 [0.86041181 0.22432493 0.64168503]]


here i reshaped an array of dimensions 3x2 to an array of dimensions 2x3

In [15]:
# Example 2 - working
arr = np.random.rand(4,2,3)
print('Initial array shape : ',arr.shape,'\n',arr,'\n')
reshaped = np.reshape(arr,(3,4,2))
print('Output array shape : ',reshaped.shape,'\n',reshaped)

Initial array shape :  (4, 2, 3) 
 [[[0.87707701 0.35258122 0.97430322]
  [0.52122373 0.79766324 0.63734888]]

 [[0.3816141  0.65807557 0.89687492]
  [0.0627754  0.30126169 0.56808151]]

 [[0.40435513 0.70548541 0.07094767]
  [0.62254618 0.70839441 0.95413531]]

 [[0.64081239 0.78323455 0.37376139]
  [0.44636898 0.5271526  0.30935453]]] 

Output array shape :  (3, 4, 2) 
 [[[0.87707701 0.35258122]
  [0.97430322 0.52122373]
  [0.79766324 0.63734888]
  [0.3816141  0.65807557]]

 [[0.89687492 0.0627754 ]
  [0.30126169 0.56808151]
  [0.40435513 0.70548541]
  [0.07094767 0.62254618]]

 [[0.70839441 0.95413531]
  [0.64081239 0.78323455]
  [0.37376139 0.44636898]
  [0.5271526  0.30935453]]]


here i reshaped an array of dimensions 4x2x3 to an array of dimensions 3x4x2

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.random.rand(1,2,3)
print('initial array : ',arr,'\n')
print('After reshape : ',np.reshape(arr,(1,3)))

initial array :  [[[0.75003518 0.80527129 0.44164234]
  [0.8751198  0.80727466 0.59460272]]] 



ValueError: cannot reshape array of size 6 into shape (1,3)

The size of the new matrix should be same as the size of old matrix.

This function can be used when we need to reshape an array to desired shape

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "akhilesharma47/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/akhilesharma47/numpy-array-operations


'https://jovian.ml/akhilesharma47/numpy-array-operations'

## Function 3 - np.stack

Join a sequence of arrays along a new axis.

In [18]:
# Example 1 - working
a = np.array([1,23,4])
b = np.array([2,3,1])
np.stack((a,b),axis=0)

array([[ 1, 23,  4],
       [ 2,  3,  1]])

The arrays are stacked one above another.

In [19]:
# Example 2 - working
a = np.array([1,23,4])
b = np.array([2,3,1])
np.stack((a,b),axis=1)

array([[ 1,  2],
       [23,  3],
       [ 4,  1]])

The array are stacked above each other along axis = 1.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([1,23])
a.resize()
b = np.array([2,3,1])
np.stack((a,b),axis=2)

ValueError: all input arrays must have the same shape

All the arrays to be stacked should have the same shape. Thus we need to resize or reshape all the arrays to be of same shape.

This function can be used to satcks various arrays on top of each other.

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "akhilesharma47/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/akhilesharma47/numpy-array-operations


'https://jovian.ml/akhilesharma47/numpy-array-operations'

## Function 4 - np.mean

Compute the arithmetic mean along the specified axis.

In [22]:
# Example 1 - working
a = np.random.rand(4)
print(a)
print('mean : ', np.mean(a))

[0.9512448  0.90101473 0.46384868 0.46089669]
mean :  0.6942512258526566


The mean of the array along axis = 0

In [23]:
# Example 2 - working
a = np.random.rand(2,3)
print(a)
print('mean : ', np.mean(a, axis = 1))

[[0.25117144 0.78326095 0.21254879]
 [0.90359264 0.74364447 0.25473597]]
mean :  [0.41566039 0.63399102]


The mean of the array along axis = 1

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[2,3],[1,2],[4,2,3]])
print(a)
print('mean : ', np.mean(a))

[list([2, 3]) list([1, 2]) list([4, 2, 3])]


<ipython-input-24-34cb3546f41c>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a = np.array([[2,3],[1,2],[4,2,3]])


TypeError: unsupported operand type(s) for /: 'list' and 'int'

The function breaks down if we provide a vector of size other than the vectors used.

This function can be used to calculate mean of an array.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "akhilesharma47/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/akhilesharma47/numpy-array-operations


'https://jovian.ml/akhilesharma47/numpy-array-operations'

## Function 5 - np.linalg.solve

Solve a linear matrix equation, or system of linear scalar equations.

In [26]:
# Example 1 - working
a = np.array([[1,1,-1],
     [1,-1,1],
     [-1,1,1]])
b= np.array([1,0,-1])

x = np.linalg.solve(a, b)
print('x =',x)
print('a * x = ',np.matmul(a, x), ' = b')

x = [ 0.5 -0.  -0.5]
a * x =  [ 1.  0. -1.]  = b


It calculates the system of given equations and outputs the results.

In [27]:
# Example 2 - working
a = np.array([[1,3,-1],
     [2,-1,2],
     [3,2,-1]])
b= np.array([12,2,4])

x = np.linalg.solve(a, b)
print('x =',x)
print('a * x = ',np.matmul(a, x), ' = b')

x = [-1.  6.  5.]
a * x =  [12.  2.  4.]  = b


It calculates the system of given equations and outputs the results.

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[1,3,-1],
     [2,6,-2],
     [4,12,-4]])
b= np.array([12,2,4])

x = np.linalg.solve(a, b)

print('a * x = ',np.matmul(a, x), ' = b')

LinAlgError: Singular matrix

The function breaks down if the matrix is singular.

This function can be used to calculate the solution of linear equations quickly.

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "akhilesharma47/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/akhilesharma47/numpy-array-operations


'https://jovian.ml/akhilesharma47/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "akhilesharma47/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/akhilesharma47/numpy-array-operations


'https://jovian.ml/akhilesharma47/numpy-array-operations'